### PR TITLE
[1.x] Migrate validation rule class from Rule to Validation rule

### PR DESCRIPTION
**Pull request by kiankamgar**
Migrate validation rule class from Rule (`Illuminate\Contracts\Validation\Rule`) to `ValidationRule(Illuminate\Contracts\Validation\ValidationRule`)

### CODE REVIEW

**Comment by kiankamgar** [comment]
I think test errors is because ValidationRule class is not available in laravel < 10

**Comment by kiankamgar** [comment]
If its time to merge this pull request, let me know to refactor it and update it as project last version

**Comment by milwad-dev** [comment]
Create a new PR and get new updates.

**Comment by kiankamgar** [comment]
Ok

**Pull request closed without merging**
