### PR TITLE
[1.x] Support Laravel 11

### PR DESCRIPTION
**Pull request by milwad-dev**

### CODE REVIEW

**Comment by websitevirtuoso** [comment]
Can we merge it?

```
Problem 1
    - Root composer.json requires milwad/laravel-validate ^1.7.2 -> satisfiable by milwad/laravel-validate[v1.7.2].
    - milwad/laravel-validate v1.7.2 requires laravel/framework 9.*|10.* -> found laravel/framework[v9.0.0-beta.1, ..., v9.52.16, v10.0.0, ..., v10.48.2] but it conflicts with your root composer.json require (^v11.0.5).
```

**Comment by oracast** [comment]
any news?

**Comment by khalidmaquilang** [comment]
```
Problem 1
    - milwad/laravel-validate v1.8.0 requires morilog/jalali 3.* -> satisfiable by morilog/jalali[v3.0.0, ..., v3.4.1].
    - milwad/laravel-validate[v1.0, ..., v1.3] require laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - milwad/laravel-validate v1.4 requires laravel/framework ^7.0|^8.0|^9.0 -> found laravel/framework[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - milwad/laravel-validate[v1.6, ..., v1.7.2] require laravel/framework 9.*|10.* -> found laravel/framework[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.8] but it conflicts with your root composer.json require (^11.0).
    - morilog/jalali[v3.0.0, ..., v3.0.2] require illuminate/support ^5.0 -> found illuminate/support[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - morilog/jalali[v3.0.3, ..., v3.0.8] require nesbot/carbon ^1.21 -> found nesbot/carbon[1.21.0, ..., 1.39.1] but the package is fixed to 3.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - morilog/jalali v3.0.9 requires php ^7.0 -> your php version (8.3.6) does not satisfy that requirement.
    - morilog/jalali[v3.0.10, ..., v3.1.2] require php ^7.0 | ^7.1 | ^7.2 -> your php version (8.3.6) does not satisfy that requirement.
    - morilog/jalali[v3.2.0, ..., v3.4.1] require nesbot/carbon ^1.21 || ^2.0 -> found nesbot/carbon[1.21.0, ..., 1.39.1, 2.0.0, ..., 2.72.3] but the package is fixed to 3.2.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires milwad/laravel-validate * -> satisfiable by milwad/laravel-validate[v1.0, ..., v1.8.0].
```
laravel 11

**Comment by milwad-dev** [comment]
Fix

**Pull request merged**
